### ISSUE TITLE
591 網頁有更新

### ISSUE THREAD

**Issue by haruzheng** [ceshine/591scraper#1]
Hi

```
browser.find_element_by_css_selector(
            f"dd[data-id=\"{region}\"]").click()
```

環境建好之後，發現 `dd[data-id=\"{region}\"]` 物件好像不存在了，
但因為不知道原本的網頁上的 CSS 是甚麼，所以不知道怎麼改起。

謝謝

**Comment by haruzheng** [comment]
我最後是自己串 591 的 api 路徑拿到資料
不過需要手動換 token

**Comment by ceshine** [comment]
謝謝回報。

```
  try:
      browser.find_element_by_css_selector(f'dd[data-id="{region}"]').click()
  except NoSuchElementException:
      pass
```

這部分是處理舊版網頁需要點選地區才能正確篩選物件的問題，對於新版網頁可以直接忽略。

`collect_list.py` 的部分其實只需要[更新物件的路徑](https://github.com/ceshine/591scraper/pull/2/commits/9b03dc77063a4d3106fde172113057189bea38c6)就可以解決。

另外，我發現 591 現在好像有在擋 requests，所以 `fetch_info.py` 會收到 404 responses。目前更改 user agent 能解決問題。

`fetch_info.py` 的欄目路徑看起來也得更新，暫時沒時間處理，之後有時間再來改

**Comment by ceshine** [comment]
已在 #2 完成針對新版網頁的修正。
